import type {
  DungeonPayout,
  PayoutClearItem,
  PayoutCrateDrop,
} from "./dungeon-payout-types"

function esc(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
}

function dropElement(d: PayoutCrateDrop, indent: string): string {
  const lines = [
    `${indent}<element>`,
    `${indent}    <object>`,
    `${indent}        <member name="ItemType">${d.itemId}</member>`,
    `${indent}        <member name="MinStack">${d.minStack}</member>`,
    `${indent}        <member name="MaxStack">${d.maxStack}</member>`,
    `${indent}        <member name="Rate">${d.rate}</member>`,
  ]
  if (d.mutexId != null && d.mutexId > 0) {
    lines.push(
      `${indent}        <member name="MutexID">${d.mutexId}</member>`
    )
  }
  lines.push(`${indent}    </object>`, `${indent}</element>`)
  return lines.join("\n")
}

export function generateDropSetXml(payout: DungeonPayout): string {
  const drops = payout.crateDrops.map((d) => dropElement(d, "            ")).join("\n")
  return `<objects>
    <!--
      Generated by Phase 16D payout editor from ${esc(payout.id)}.
      DropSet ${payout.dropSetId} — ${esc(payout.name)}
    -->
    <object name="DropSet">
        <member name="ID">${payout.dropSetId}</member>
        <desc>${esc(payout.name)} clear crate</desc>
        <member name="Drops">
${drops}
        </member>
    </object>
</objects>
`
}

function spotElements(count: number, spotId: number, indent: string): string {
  return Array.from({ length: count }, () =>
    [
      `${indent}<element>`,
      `${indent}    <object>`,
      `${indent}        <member name="SpotID">${spotId}</member>`,
      `${indent}    </object>`,
      `${indent}</element>`,
    ].join("\n")
  ).join("\n")
}

function clearItemActions(
  items: PayoutClearItem[],
  indent: string
): string {
  if (!items.length) return ""
  const pairs = items
    .map(
      (it) =>
        `${indent}            <pair>
${indent}                <key>${it.itemId}</key>
${indent}                <value>${it.quantity}</value>
${indent}            </pair>`
    )
    .join("\n")
  return `
${indent}<element>
${indent}    <object name="ActionAddRemoveItems">
${indent}        <member name="sourceContext">ALL</member>
${indent}        <member name="location">INSTANCE</member>
${indent}        <member name="notify">true</member>
${indent}        <member name="items">
${pairs}
${indent}        </member>
${indent}    </object>
${indent}</element>`
}

function bonusActionsXml(payout: DungeonPayout, indent: string): string {
  const clear = clearItemActions(payout.clearItems, indent)
  const loot =
    payout.crateCount > 0
      ? `${indent}<element>
${indent}    <object name="ActionCreateLoot">
${indent}        <member name="sourceContext">SOURCE</member>
${indent}        <member name="location">ZONE</member>
${indent}        <member name="stopOnFailure">false</member>
${indent}        <member name="isBossBox">true</member>
${indent}        <member name="bossGroupID">${payout.bossGroupId}</member>
${indent}        <member name="dropSetIDs">
${indent}            <element>${payout.dropSetId}</element>
${indent}        </member>
${indent}        <member name="locations">
${spotElements(payout.crateCount, payout.spotId, `${indent}                `)}
${indent}        </member>
${indent}    </object>
${indent}</element>`
      : ""
  // Dedup flag first; CP before loot (stock defeat chains often fire with no
  // player client — PARTY CP would be skipped). CreateLoot must not abort CP.
  return `${indent}<element>
${indent}    <object name="ActionUpdateZoneFlags">
${indent}        <member name="type">ZONE_INSTANCE</member>
${indent}        <member name="flagStates">
${indent}            <pair>
${indent}                <key>${payout.dedupFlag}</key>
${indent}                <value>1</value>
${indent}            </pair>
${indent}        </member>
${indent}    </object>
${indent}</element>
${indent}<element>
${indent}    <object name="ActionUpdatePoints">
${indent}        <member name="sourceContext">ALL</member>
${indent}        <member name="location">INSTANCE</member>
${indent}        <member name="pointType">CP</member>
${indent}        <member name="value">${payout.cp}</member>
${indent}    </object>
${indent}</element>${loot}${clear}`
}

function payoutInstanceIds(payout: DungeonPayout): number[] {
  const ids = payout.instanceIds?.length
    ? payout.instanceIds
    : [payout.instanceId]
  return [...new Set(ids)].sort((a, b) => a - b)
}

function branchGateXml(payout: DungeonPayout, nextId: string, indent: string): string {
  const instanceParams = payoutInstanceIds(payout)
    .map((id) => `${indent}                        <element>${id}</element>`)
    .join("\n")
  return `${indent}<element>
${indent}    <object>
${indent}        <member name="next">${esc(nextId)}</member>
${indent}        <member name="conditions">
${indent}            <element>
${indent}                <object name="EventScriptCondition">
${indent}                    <member name="scriptID">bool_currentInstance</member>
${indent}                    <member name="params">
${instanceParams}
${indent}                    </member>
${indent}                </object>
${indent}            </element>
${indent}            <element>
${indent}                <object name="EventFlagCondition">
${indent}                    <member name="type">ZONE_INSTANCE_FLAGS</member>
${indent}                    <member name="compareMode">LT_OR_NAN</member>
${indent}                    <member name="flagStates">
${indent}                        <pair>
${indent}                            <key>${payout.dedupFlag}</key>
${indent}                            <value>1</value>
${indent}                        </pair>
${indent}                    </member>
${indent}                </object>
${indent}            </element>
${indent}        </member>
${indent}    </object>
${indent}</element>`
}

/**
 * Shared AFTER_* dispatcher for payouts that share the same stock splice IDs
 * (e.g. Suginami bronze/silver/gold). One Event with N instance branches.
 */
export function generateSharedAfterEventsXml(payouts: DungeonPayout[]): string {
  if (!payouts.length) {
    throw new Error("generateSharedAfterEventsXml requires at least one payout")
  }
  const head = payouts[0]
  const afterNormal = head.hooks.afterNormalLootEventId
  const afterFiend = head.hooks.afterFiendLootEventId
  const resume = head.hooks.resumeNormalNext
  for (const p of payouts) {
    if (p.hooks.afterNormalLootEventId !== afterNormal) {
      throw new Error(
        `Shared AFTER normal mismatch: ${head.id} vs ${p.id} (${afterNormal} vs ${p.hooks.afterNormalLootEventId})`
      )
    }
    if (p.hooks.afterFiendLootEventId !== afterFiend) {
      throw new Error(
        `Shared AFTER fiend mismatch: ${head.id} vs ${p.id} (${afterFiend} vs ${p.hooks.afterFiendLootEventId})`
      )
    }
    if (p.hooks.resumeNormalNext !== resume) {
      throw new Error(
        `Shared resume mismatch: ${head.id} vs ${p.id} (${resume} vs ${p.hooks.resumeNormalNext})`
      )
    }
  }

  const ids = payouts.map((p) => p.id).join(", ")
  const branchNormal = payouts
    .map((p) => branchGateXml(p, p.hooks.bonusEventId, "            "))
    .join("\n")
  const branchFiend = payouts
    .map((p) => branchGateXml(p, p.hooks.bonusFiendEventId, "            "))
    .join("\n")

  return `<objects>
    <!--
      Shared clear dispatcher for: ${esc(ids)}.
      Stock loot events must next → ${esc(afterNormal)} / ${esc(afterFiend)}.
    -->
    <object name="Event">
        <member name="ID">${esc(afterNormal)}</member>
        <member name="next">${esc(resume)}</member>
        <member name="branches">
${branchNormal}
        </member>
    </object>

    <object name="Event">
        <member name="ID">${esc(afterFiend)}</member>
        <member name="branches">
${branchFiend}
        </member>
    </object>
</objects>
`
}

/** Per-payout CLEAR_BONUS / CLEAR_BONUS_FIEND only (AFTER lives in shared file). */
export function generateBonusOnlyEventsXml(payout: DungeonPayout): string {
  const h = payout.hooks
  const actions = bonusActionsXml(payout, "            ")
  return `<objects>
    <!--
      Bonus actions for ${esc(payout.id)} (instance ${payout.instanceId}).
      Reached via shared AFTER dispatcher → ${esc(h.bonusEventId)}.
    -->
    <object name="EventPerformActions">
        <member name="ID">${esc(h.bonusEventId)}</member>
        <member name="next">${esc(h.resumeNormalNext)}</member>
        <member name="actions">
${actions}
        </member>
    </object>

    <object name="EventPerformActions">
        <member name="ID">${esc(h.bonusFiendEventId)}</member>
        <member name="actions">
${actions}
        </member>
    </object>
</objects>
`
}

/** Full single-payout package (solo export / single-member family). */
export function generateEventsXml(payout: DungeonPayout): string {
  const shared = generateSharedAfterEventsXml([payout])
  const bonus = generateBonusOnlyEventsXml(payout)
  // Merge <objects>…</objects> bodies
  const sharedBody = shared
    .replace(/^<objects>\s*/i, "")
    .replace(/\s*<\/objects>\s*$/i, "")
  const bonusBody = bonus
    .replace(/^<objects>\s*/i, "")
    .replace(/\s*<\/objects>\s*$/i, "")
  return `<objects>
${sharedBody}

${bonusBody}
</objects>
`
}

export function payoutPackagePaths(payout: DungeonPayout): {
  eventsPath: string
  dropSetPath: string
} {
  return {
    eventsPath: `events/ai_custom_payout_${payout.id}.xml`,
    dropSetPath: `data/dropset/ai_custom_payout_${payout.id}.xml`,
  }
}

/** Stable zip path for a shared AFTER dispatcher group. */
export function sharedAfterPackagePath(afterNormalLootEventId: string): string {
  const slug = afterNormalLootEventId
    .replace(/^AI_PAY_/i, "")
    .replace(/_AFTER_NORMAL$/i, "")
    .replace(/[^a-zA-Z0-9_-]+/g, "_")
    .toLowerCase()
  return `events/ai_custom_payout_dispatch_${slug || "shared"}.xml`
}
