import type {
  DungeonPayout,
  PayoutClearItem,
  PayoutCrateDrop,
} from "./dungeon-payout-types"

function esc(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
}

function dropElement(d: PayoutCrateDrop, indent: string): string {
  const lines = [
    `${indent}<element>`,
    `${indent}    <object>`,
    `${indent}        <member name="ItemType">${d.itemId}</member>`,
    `${indent}        <member name="MinStack">${d.minStack}</member>`,
    `${indent}        <member name="MaxStack">${d.maxStack}</member>`,
    `${indent}        <member name="Rate">${d.rate}</member>`,
  ]
  if (d.mutexId != null && d.mutexId > 0) {
    lines.push(
      `${indent}        <member name="MutexID">${d.mutexId}</member>`
    )
  }
  lines.push(`${indent}    </object>`, `${indent}</element>`)
  return lines.join("\n")
}

export function generateDropSetXml(payout: DungeonPayout): string {
  const drops = payout.crateDrops.map((d) => dropElement(d, "            ")).join("\n")
  return `<objects>
    <!--
      Generated by Phase 16D payout editor from ${esc(payout.id)}.
      DropSet ${payout.dropSetId} — ${esc(payout.name)}
    -->
    <object name="DropSet">
        <member name="ID">${payout.dropSetId}</member>
        <desc>${esc(payout.name)} clear crate</desc>
        <member name="Drops">
${drops}
        </member>
    </object>
</objects>
`
}

function spotElements(count: number, spotId: number, indent: string): string {
  return Array.from({ length: count }, () =>
    [
      `${indent}<element>`,
      `${indent}    <object>`,
      `${indent}        <member name="SpotID">${spotId}</member>`,
      `${indent}    </object>`,
      `${indent}</element>`,
    ].join("\n")
  ).join("\n")
}

function clearItemActions(
  items: PayoutClearItem[],
  indent: string
): string {
  if (!items.length) return ""
  const pairs = items
    .map(
      (it) =>
        `${indent}            <pair>
${indent}                <key>${it.itemId}</key>
${indent}                <value>${it.quantity}</value>
${indent}            </pair>`
    )
    .join("\n")
  return `
${indent}<element>
${indent}    <object name="ActionAddRemoveItems">
${indent}        <member name="sourceContext">PARTY</member>
${indent}        <member name="location">INSTANCE</member>
${indent}        <member name="notify">true</member>
${indent}        <member name="items">
${pairs}
${indent}        </member>
${indent}    </object>
${indent}</element>`
}

function bonusActionsXml(payout: DungeonPayout, indent: string): string {
  const spots = spotElements(payout.crateCount, payout.spotId, `${indent}                `)
  const clear = clearItemActions(payout.clearItems, indent)
  return `${indent}<element>
${indent}    <object name="ActionUpdateZoneFlags">
${indent}        <member name="type">ZONE_INSTANCE</member>
${indent}        <member name="flagStates">
${indent}            <pair>
${indent}                <key>${payout.dedupFlag}</key>
${indent}                <value>1</value>
${indent}            </pair>
${indent}        </member>
${indent}    </object>
${indent}</element>
${indent}<element>
${indent}    <object name="ActionCreateLoot">
${indent}        <member name="sourceContext">SOURCE</member>
${indent}        <member name="location">ZONE</member>
${indent}        <member name="isBossBox">true</member>
${indent}        <member name="bossGroupID">${payout.bossGroupId}</member>
${indent}        <member name="dropSetIDs">
${indent}            <element>${payout.dropSetId}</element>
${indent}        </member>
${indent}        <member name="locations">
${spots}
${indent}        </member>
${indent}    </object>
${indent}</element>
${indent}<element>
${indent}    <object name="ActionUpdatePoints">
${indent}        <member name="sourceContext">PARTY</member>
${indent}        <member name="location">INSTANCE</member>
${indent}        <member name="pointType">CP</member>
${indent}        <member name="value">${payout.cp}</member>
${indent}    </object>
${indent}</element>${clear}`
}

function branchGateXml(payout: DungeonPayout, nextId: string, indent: string): string {
  return `${indent}<element>
${indent}    <object>
${indent}        <member name="next">${esc(nextId)}</member>
${indent}        <member name="conditions">
${indent}            <element>
${indent}                <object name="EventScriptCondition">
${indent}                    <member name="scriptID">bool_currentInstance</member>
${indent}                    <member name="params">
${indent}                        <element>${payout.instanceId}</element>
${indent}                    </member>
${indent}                </object>
${indent}            </element>
${indent}            <element>
${indent}                <object name="EventFlagCondition">
${indent}                    <member name="type">ZONE_INSTANCE_FLAGS</member>
${indent}                    <member name="compareMode">LT_OR_NAN</member>
${indent}                    <member name="flagStates">
${indent}                        <pair>
${indent}                            <key>${payout.dedupFlag}</key>
${indent}                            <value>1</value>
${indent}                        </pair>
${indent}                    </member>
${indent}                </object>
${indent}            </element>
${indent}        </member>
${indent}    </object>
${indent}</element>`
}

export function generateEventsXml(payout: DungeonPayout): string {
  const h = payout.hooks
  const branchNormal = branchGateXml(payout, h.bonusEventId, "            ")
  const branchFiend = branchGateXml(payout, h.bonusFiendEventId, "            ")
  const actions = bonusActionsXml(payout, "            ")

  return `<objects>
    <!--
      Generated by Phase 16D payout editor from ${esc(payout.id)}.
      Instance ${payout.instanceId} — ${esc(payout.name)}
      Stock loot events must next → ${esc(h.afterNormalLootEventId)} /
      ${esc(h.afterFiendLootEventId)} (one-time datastore patch).
    -->
    <object name="Event">
        <member name="ID">${esc(h.afterNormalLootEventId)}</member>
        <member name="next">${esc(h.resumeNormalNext)}</member>
        <member name="branches">
${branchNormal}
        </member>
    </object>

    <object name="Event">
        <member name="ID">${esc(h.afterFiendLootEventId)}</member>
        <member name="branches">
${branchFiend}
        </member>
    </object>

    <object name="EventPerformActions">
        <member name="ID">${esc(h.bonusEventId)}</member>
        <member name="next">${esc(h.resumeNormalNext)}</member>
        <member name="actions">
${actions}
        </member>
    </object>

    <object name="EventPerformActions">
        <member name="ID">${esc(h.bonusFiendEventId)}</member>
        <member name="actions">
${actions}
        </member>
    </object>
</objects>
`
}

export function payoutPackagePaths(payout: DungeonPayout): {
  eventsPath: string
  dropSetPath: string
} {
  return {
    eventsPath: `events/ai_custom_payout_${payout.id}.xml`,
    dropSetPath: `data/dropset/ai_custom_payout_${payout.id}.xml`,
  }
}
