/**
 * Clear-loot catalog (generated by scripts/payout-scan-clear-loot.py).
 * Used by /admin/payouts to show whether beating a dungeon can grant CP.
 */
import { promises as fs } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

export type PayoutWireStatusCode =
  | "wired"
  | "partial"
  | "hooks_ready"
  | "unwired_stub"

export type PayoutWireStatus = {
  payoutId: string
  status: PayoutWireStatusCode
  enabled: boolean
  instanceId?: number
  instanceExists: boolean
  resumeTodo: boolean
  stockWired: boolean
  stockEventsPointingAtNormal: string[]
  stockEventsPointingAtFiend: string[]
  candidateClearLootEventIds: string[]
  issues: string[]
  liveEffect: string
}

export type ClearLootCatalogSummary = {
  clearLootEventCount: number
  zoneInstanceCount: number
  payoutCount: number
  payoutStatusCounts: Record<string, number>
  enabledWired: number
  enabledUnwired: number
}

export type ClearLootCatalogEvent = {
  eventId: string
  next?: string | null
  sourceFile?: string
  [key: string]: unknown
}

type CatalogFile = {
  version: number
  generatedAt?: string
  summary?: ClearLootCatalogSummary
  clearLootEvents?: ClearLootCatalogEvent[]
  wireStatus?: PayoutWireStatus[]
}

function catalogPath(): string {
  if (process.env.COMP_PAYOUTS_DIR?.trim()) {
    return path.join(
      path.resolve(process.env.COMP_PAYOUTS_DIR.trim()),
      "clear-loot-catalog.json"
    )
  }
  return path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "../../server-content/payouts/clear-loot-catalog.json"
  )
}

let cache: { mtimeMs: number; data: CatalogFile } | null = null

export async function loadClearLootCatalog(): Promise<CatalogFile | null> {
  const file = catalogPath()
  try {
    const st = await fs.stat(file)
    if (cache && cache.mtimeMs === st.mtimeMs) return cache.data
    const raw = JSON.parse(await fs.readFile(file, "utf8")) as CatalogFile
    cache = { mtimeMs: st.mtimeMs, data: raw }
    return raw
  } catch {
    return null
  }
}

export async function getPayoutWireStatusMap(): Promise<
  Map<string, PayoutWireStatus>
> {
  const catalog = await loadClearLootCatalog()
  const map = new Map<string, PayoutWireStatus>()
  for (const row of catalog?.wireStatus ?? []) {
    map.set(row.payoutId, row)
  }
  return map
}

export async function getPayoutWireStatus(
  payoutId: string
): Promise<PayoutWireStatus | null> {
  const map = await getPayoutWireStatusMap()
  return map.get(payoutId) ?? null
}

/** True when enabling would still not pay out on clear. */
export function isUnwiredForLive(status: PayoutWireStatus | null): boolean {
  if (!status) return true
  return status.status !== "wired"
}

export function wireStatusLabel(status: PayoutWireStatusCode): string {
  switch (status) {
    case "wired":
      return "Live-wired"
    case "partial":
      return "Partially wired"
    case "hooks_ready":
      return "Hooks ready (stock not patched)"
    case "unwired_stub":
      return "Not mapped yet"
    default:
      return status
  }
}
